### ISSUE TITLE
Logitech G27 Shift Gear 5 and 6 not recognised

### ISSUE THREAD

**Issue by Silencx** [dmadison/Sim-Racing-Arduino#10]
I've got a problem with the code not detecting gear 5 and 6.
It recognizing gear 5 as gear 3 and gear 6 as reverse or gear 4.
I've already tried reading out the x/y coordinates and then setting a custom calibration but with no luck.
It just does not want to recognize the gears.

I'm using your custom pcb with a sparkpro.

**Comment by dmadison** [comment]
Hello, and sorry to hear that you're having issues.

Can you please provide some more information:

* Are you using the ATMega32U4 Pro Micro or the RP2040 Pro Micro?
* Are you using code from one of the library examples? If not, what code are you using?
* Have you modified the object declaration to use the `SHIFTER_SHIELD_V1_PINS`?
* What calibration data are you attempting to use? Have you tried adjusting the "Horizontal Gate Offset" value?

**Comment by Silencx** [comment]
Hello, as for your questions.

**Are you using the ATMega32U4 Pro Micro or the RP2040 Pro Micro?** 
- I'm using a ATMega32U4 Pro micro

**Are you using code from one of the library examples? If not, what code are you using?**
- I'm using the `ShiftJoystick `example.

**Have you modified the object declaration to use the SHIFTER_SHIELD_V1_PINS?**
- I've tried using the SHIFTER_SHIELD_V1_PINS in the object declaration it does recognize the shifter when using the preset, but then it gives the problem that it doesn't recognizes the gears.

**What calibration data are you attempting to use? Have you tried adjusting the "Horizontal Gate Offset" value?**
- The calibration data was the x/y locations of the gears that i found using the `ShiftPrint `example. I've shifted in to the gear multiple times and then found the average x/y per gear and used those to create the calibration. I didn't know what value to use on the `engagePoint`, `releasePoint `and `edgeOffset`. So i just used 0 then 0,5 and then 1 on them all.

**Comment by dmadison** [comment]
Thank you for following up and answering those questions.

>The calibration data was the x/y locations of the gears that i found using the ShiftPrint example

Could you please share what those values are for each position? Neutral, 1-6 and reverse.

**Comment by Silencx** [comment]
These was the calibaration that i used:
`shifter.setCalibration({370,630},{156, 708},{156, 180},{375, 708},{375, 175},{616, 908},{616, 175});`
this is neurtal and 1-6 as it didnt state that i could use reverse as a gear in the documentation of the function.

**Comment by dmadison** [comment]
Thank you. Yes, the calibration function does not use the reverse position, but it's useful to know the position for debugging. In theory it should be close enough to 6th gear that the difference doesn't matter.

This is going to be a long response. Let me take a minute to explain how the shifter position is calculated.

The calibration function averages the X and Y values from matching gears to find the limits of the shifter axes. It then applies these limits to the analog axis class to define the min/max values of each axis.

From there it calculates the normalized neutral axis position within that box, and then calculates the difference from the neutral position to the X and Y min/max. That difference on Y is multiplied by the engagement point to find the threshold when the shifter is considered "in gear', and multiplied by the release point to find the threshold when the shifter leaves gear. The area between those two points acts as a hysteresis buffer.

A similar calculation occurs for the left/right gear selection, where the distance from the edge of the calibrated X axis to the neutral position X is multiplied by the edge offset to find the thresholds where gears are considered low/high or centered.

It's important to note that the left/right selection only affects what gear is calculated when the shifter is moved past the Y threshold into gear and not beforehand. Which means if you're not getting into 5/6 it would make sense that you aren't passing the high-side X threshold reliably.

---

Currently [the default calibration](https://github.com/dmadison/Sim-Racing-Arduino/blob/4a291e4fdb7b88f0a1e394b6a87a39165e3d5983/src/SimRacing.cpp#L983) is as follows:
```
Neutral: (490, 440)
    1st: (253, 799)
    2nd: (262, 86)
    3rd: (460, 826)
    4th: (470, 76)
    5th: (664, 841)
    6th: (677, 77)
```

By default, the engagement point is set to 0.7, the release point is set to 0.5, and the edge offset is set to 0.7, giving us the following internal calibration values:
```
X Min: 257
X Max: 670
Y Min: 79
Y Max: 822

Odd Trigger: 865
Odd Release: 760
Even Trigger: 149
Even Release: 248
Left Edge: 173
Right Edge: 889
```

These may look a little odd, because the trigger/release values are normalized to the calibrated input range. Shifter axis values below the min/max are truncated, and all running calculations are done in the 0-1023 space.

---

Now from your post above you're using:
```
Neutral: (370, 630)
    1st: (156, 708)
    2nd: (156, 180)
    3rd: (375, 708)
    4th: (375, 175)
    5th: (616, 908)
    6th: (616, 175)
```

I'm assuming the 908 for the Y axis of the 5th gear is a typo and it's supposed to be 708? It's strange that it's significantly longer than the other gears, and from brief testing that prevents the shifter from going into gears 1/3, which is not your reported problem.

With 908 on the 5th gear replaced by 708, here's the internal calibration:
```
X Min: 156
X Max: 616
Y Min: 176
Y Max: 708

Odd Trigger: 978
Odd Release: 948
Even Trigger: 261
Even Release: 436
Left Edge: 142
Right Edge: 858
```

Here are the results using those same gear positions as simulated inputs with your calibration:
```
Gear n (475, 873)   - n
Gear 1 (0, 1023)    - 1
Gear 2 (0, 7)       - 2
Gear 3 (487, 1023)  - 3
Gear 4 (487, 0)     - 4
Gear 5 (1023, 1023) - 5
Gear 6 (1023, 0)    - 6
```
No issues there. Now let's try those same gear positions as simulated inputs, using the default calibration:
```
Gear n (279, 758)  - n
Gear 1 (0, 866)    - 1
Gear 2 (0, 139)    - 2
Gear 3 (292, 866)  - 3
Gear 4 (292, 132)  - 4
Gear 5 (889, 1023) - 3
Gear 6 (889, 132)  - 4
```

Aha! There is our problem. Now why...

```
Odd Trigger: 865
Odd Release: 760
Even Trigger: 149
Even Release: 248
Left Edge: 173
Right Edge: 889 <--
```

Well, it appears that the right edge threshold is exactly equal to our X position of the shifter! That fails the `if (x > calibration.rightEdge)` check in the `update()` function and you can't get into 5/6th. The default calibration is just a *hair* off for the old G27 shifters and that's why there are problems.

Lowering the default calibration `edgeOffset` value from 0.7 to 0.6 fixes the problem:

```
Old Default Calibration:
-----------------
Left Edge: 173
Right Edge: 889

New Calibration:
-----------------
Left Edge: 230
Right Edge: 844
```

With your shifter positions:
```
Gear n (279, 758)  - n
Gear 1 (0, 866)    - 1
Gear 2 (0, 139)    - 2
Gear 3 (292, 866)  - 3
Gear 4 (292, 132)  - 4
Gear 5 (889, 1023) - 5
Gear 6 (889, 132)  - 6
```

Although that doesn't explain why your shifter isn't working with your custom calibration settings as it does on my end?

**Comment by dmadison** [comment]
I haven't heard back from you so I'm assuming this is solved. I'll push an update to the library to change that edge offset calibration which should hopefully solve the problem for others using the G27 shifter.

Feel free to reopen if you're still having issues.
